// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.aws.glue.inputs;

import com.pulumi.aws.glue.inputs.CatalogTablePartitionIndexGetArgs;
import com.pulumi.aws.glue.inputs.CatalogTablePartitionKeyGetArgs;
import com.pulumi.aws.glue.inputs.CatalogTableStorageDescriptorGetArgs;
import com.pulumi.aws.glue.inputs.CatalogTableTargetTableGetArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.core.internal.Codegen;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import javax.annotation.Nullable;


public final class CatalogTableState extends com.pulumi.resources.ResourceArgs {

    public static final CatalogTableState Empty = new CatalogTableState();

    /**
     * The ARN of the Glue Table.
     * 
     */
    @Import(name="arn")
      private final @Nullable Output<String> arn;

    public Output<String> getArn() {
        return this.arn == null ? Codegen.empty() : this.arn;
    }

    /**
     * ID of the Data Catalog in which the table resides.
     * 
     */
    @Import(name="catalogId")
      private final @Nullable Output<String> catalogId;

    public Output<String> getCatalogId() {
        return this.catalogId == null ? Codegen.empty() : this.catalogId;
    }

    /**
     * Name of the catalog database that contains the target table.
     * 
     */
    @Import(name="databaseName")
      private final @Nullable Output<String> databaseName;

    public Output<String> getDatabaseName() {
        return this.databaseName == null ? Codegen.empty() : this.databaseName;
    }

    /**
     * Description of the table.
     * 
     */
    @Import(name="description")
      private final @Nullable Output<String> description;

    public Output<String> getDescription() {
        return this.description == null ? Codegen.empty() : this.description;
    }

    /**
     * Name of the target table.
     * 
     */
    @Import(name="name")
      private final @Nullable Output<String> name;

    public Output<String> getName() {
        return this.name == null ? Codegen.empty() : this.name;
    }

    /**
     * Owner of the table.
     * 
     */
    @Import(name="owner")
      private final @Nullable Output<String> owner;

    public Output<String> getOwner() {
        return this.owner == null ? Codegen.empty() : this.owner;
    }

    /**
     * Map of initialization parameters for the SerDe, in key-value form.
     * 
     */
    @Import(name="parameters")
      private final @Nullable Output<Map<String,String>> parameters;

    public Output<Map<String,String>> getParameters() {
        return this.parameters == null ? Codegen.empty() : this.parameters;
    }

    /**
     * Configuration block for a maximum of 3 partition indexes. See `partition_index` below.
     * 
     */
    @Import(name="partitionIndices")
      private final @Nullable Output<List<CatalogTablePartitionIndexGetArgs>> partitionIndices;

    public Output<List<CatalogTablePartitionIndexGetArgs>> getPartitionIndices() {
        return this.partitionIndices == null ? Codegen.empty() : this.partitionIndices;
    }

    /**
     * Configuration block of columns by which the table is partitioned. Only primitive types are supported as partition keys. See `partition_keys` below.
     * 
     */
    @Import(name="partitionKeys")
      private final @Nullable Output<List<CatalogTablePartitionKeyGetArgs>> partitionKeys;

    public Output<List<CatalogTablePartitionKeyGetArgs>> getPartitionKeys() {
        return this.partitionKeys == null ? Codegen.empty() : this.partitionKeys;
    }

    /**
     * Retention time for this table.
     * 
     */
    @Import(name="retention")
      private final @Nullable Output<Integer> retention;

    public Output<Integer> getRetention() {
        return this.retention == null ? Codegen.empty() : this.retention;
    }

    /**
     * Configuration block for information about the physical storage of this table. For more information, refer to the [Glue Developer Guide](https://docs.aws.amazon.com/glue/latest/dg/aws-glue-api-catalog-tables.html#aws-glue-api-catalog-tables-StorageDescriptor). See `storage_descriptor` below.
     * 
     */
    @Import(name="storageDescriptor")
      private final @Nullable Output<CatalogTableStorageDescriptorGetArgs> storageDescriptor;

    public Output<CatalogTableStorageDescriptorGetArgs> getStorageDescriptor() {
        return this.storageDescriptor == null ? Codegen.empty() : this.storageDescriptor;
    }

    /**
     * Type of this table (EXTERNAL_TABLE, VIRTUAL_VIEW, etc.). While optional, some Athena DDL queries such as `ALTER TABLE` and `SHOW CREATE TABLE` will fail if this argument is empty.
     * 
     */
    @Import(name="tableType")
      private final @Nullable Output<String> tableType;

    public Output<String> getTableType() {
        return this.tableType == null ? Codegen.empty() : this.tableType;
    }

    /**
     * Configuration block of a target table for resource linking. See `target_table` below.
     * 
     */
    @Import(name="targetTable")
      private final @Nullable Output<CatalogTableTargetTableGetArgs> targetTable;

    public Output<CatalogTableTargetTableGetArgs> getTargetTable() {
        return this.targetTable == null ? Codegen.empty() : this.targetTable;
    }

    /**
     * If the table is a view, the expanded text of the view; otherwise null.
     * 
     */
    @Import(name="viewExpandedText")
      private final @Nullable Output<String> viewExpandedText;

    public Output<String> getViewExpandedText() {
        return this.viewExpandedText == null ? Codegen.empty() : this.viewExpandedText;
    }

    /**
     * If the table is a view, the original text of the view; otherwise null.
     * 
     */
    @Import(name="viewOriginalText")
      private final @Nullable Output<String> viewOriginalText;

    public Output<String> getViewOriginalText() {
        return this.viewOriginalText == null ? Codegen.empty() : this.viewOriginalText;
    }

    public CatalogTableState(
        @Nullable Output<String> arn,
        @Nullable Output<String> catalogId,
        @Nullable Output<String> databaseName,
        @Nullable Output<String> description,
        @Nullable Output<String> name,
        @Nullable Output<String> owner,
        @Nullable Output<Map<String,String>> parameters,
        @Nullable Output<List<CatalogTablePartitionIndexGetArgs>> partitionIndices,
        @Nullable Output<List<CatalogTablePartitionKeyGetArgs>> partitionKeys,
        @Nullable Output<Integer> retention,
        @Nullable Output<CatalogTableStorageDescriptorGetArgs> storageDescriptor,
        @Nullable Output<String> tableType,
        @Nullable Output<CatalogTableTargetTableGetArgs> targetTable,
        @Nullable Output<String> viewExpandedText,
        @Nullable Output<String> viewOriginalText) {
        this.arn = arn;
        this.catalogId = catalogId;
        this.databaseName = databaseName;
        this.description = description;
        this.name = name;
        this.owner = owner;
        this.parameters = parameters;
        this.partitionIndices = partitionIndices;
        this.partitionKeys = partitionKeys;
        this.retention = retention;
        this.storageDescriptor = storageDescriptor;
        this.tableType = tableType;
        this.targetTable = targetTable;
        this.viewExpandedText = viewExpandedText;
        this.viewOriginalText = viewOriginalText;
    }

    private CatalogTableState() {
        this.arn = Codegen.empty();
        this.catalogId = Codegen.empty();
        this.databaseName = Codegen.empty();
        this.description = Codegen.empty();
        this.name = Codegen.empty();
        this.owner = Codegen.empty();
        this.parameters = Codegen.empty();
        this.partitionIndices = Codegen.empty();
        this.partitionKeys = Codegen.empty();
        this.retention = Codegen.empty();
        this.storageDescriptor = Codegen.empty();
        this.tableType = Codegen.empty();
        this.targetTable = Codegen.empty();
        this.viewExpandedText = Codegen.empty();
        this.viewOriginalText = Codegen.empty();
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(CatalogTableState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable Output<String> arn;
        private @Nullable Output<String> catalogId;
        private @Nullable Output<String> databaseName;
        private @Nullable Output<String> description;
        private @Nullable Output<String> name;
        private @Nullable Output<String> owner;
        private @Nullable Output<Map<String,String>> parameters;
        private @Nullable Output<List<CatalogTablePartitionIndexGetArgs>> partitionIndices;
        private @Nullable Output<List<CatalogTablePartitionKeyGetArgs>> partitionKeys;
        private @Nullable Output<Integer> retention;
        private @Nullable Output<CatalogTableStorageDescriptorGetArgs> storageDescriptor;
        private @Nullable Output<String> tableType;
        private @Nullable Output<CatalogTableTargetTableGetArgs> targetTable;
        private @Nullable Output<String> viewExpandedText;
        private @Nullable Output<String> viewOriginalText;

        public Builder() {
    	      // Empty
        }

        public Builder(CatalogTableState defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.arn = defaults.arn;
    	      this.catalogId = defaults.catalogId;
    	      this.databaseName = defaults.databaseName;
    	      this.description = defaults.description;
    	      this.name = defaults.name;
    	      this.owner = defaults.owner;
    	      this.parameters = defaults.parameters;
    	      this.partitionIndices = defaults.partitionIndices;
    	      this.partitionKeys = defaults.partitionKeys;
    	      this.retention = defaults.retention;
    	      this.storageDescriptor = defaults.storageDescriptor;
    	      this.tableType = defaults.tableType;
    	      this.targetTable = defaults.targetTable;
    	      this.viewExpandedText = defaults.viewExpandedText;
    	      this.viewOriginalText = defaults.viewOriginalText;
        }

        public Builder arn(@Nullable Output<String> arn) {
            this.arn = arn;
            return this;
        }
        public Builder arn(@Nullable String arn) {
            this.arn = Codegen.ofNullable(arn);
            return this;
        }
        public Builder catalogId(@Nullable Output<String> catalogId) {
            this.catalogId = catalogId;
            return this;
        }
        public Builder catalogId(@Nullable String catalogId) {
            this.catalogId = Codegen.ofNullable(catalogId);
            return this;
        }
        public Builder databaseName(@Nullable Output<String> databaseName) {
            this.databaseName = databaseName;
            return this;
        }
        public Builder databaseName(@Nullable String databaseName) {
            this.databaseName = Codegen.ofNullable(databaseName);
            return this;
        }
        public Builder description(@Nullable Output<String> description) {
            this.description = description;
            return this;
        }
        public Builder description(@Nullable String description) {
            this.description = Codegen.ofNullable(description);
            return this;
        }
        public Builder name(@Nullable Output<String> name) {
            this.name = name;
            return this;
        }
        public Builder name(@Nullable String name) {
            this.name = Codegen.ofNullable(name);
            return this;
        }
        public Builder owner(@Nullable Output<String> owner) {
            this.owner = owner;
            return this;
        }
        public Builder owner(@Nullable String owner) {
            this.owner = Codegen.ofNullable(owner);
            return this;
        }
        public Builder parameters(@Nullable Output<Map<String,String>> parameters) {
            this.parameters = parameters;
            return this;
        }
        public Builder parameters(@Nullable Map<String,String> parameters) {
            this.parameters = Codegen.ofNullable(parameters);
            return this;
        }
        public Builder partitionIndices(@Nullable Output<List<CatalogTablePartitionIndexGetArgs>> partitionIndices) {
            this.partitionIndices = partitionIndices;
            return this;
        }
        public Builder partitionIndices(@Nullable List<CatalogTablePartitionIndexGetArgs> partitionIndices) {
            this.partitionIndices = Codegen.ofNullable(partitionIndices);
            return this;
        }
        public Builder partitionIndices(CatalogTablePartitionIndexGetArgs... partitionIndices) {
            return partitionIndices(List.of(partitionIndices));
        }
        public Builder partitionKeys(@Nullable Output<List<CatalogTablePartitionKeyGetArgs>> partitionKeys) {
            this.partitionKeys = partitionKeys;
            return this;
        }
        public Builder partitionKeys(@Nullable List<CatalogTablePartitionKeyGetArgs> partitionKeys) {
            this.partitionKeys = Codegen.ofNullable(partitionKeys);
            return this;
        }
        public Builder partitionKeys(CatalogTablePartitionKeyGetArgs... partitionKeys) {
            return partitionKeys(List.of(partitionKeys));
        }
        public Builder retention(@Nullable Output<Integer> retention) {
            this.retention = retention;
            return this;
        }
        public Builder retention(@Nullable Integer retention) {
            this.retention = Codegen.ofNullable(retention);
            return this;
        }
        public Builder storageDescriptor(@Nullable Output<CatalogTableStorageDescriptorGetArgs> storageDescriptor) {
            this.storageDescriptor = storageDescriptor;
            return this;
        }
        public Builder storageDescriptor(@Nullable CatalogTableStorageDescriptorGetArgs storageDescriptor) {
            this.storageDescriptor = Codegen.ofNullable(storageDescriptor);
            return this;
        }
        public Builder tableType(@Nullable Output<String> tableType) {
            this.tableType = tableType;
            return this;
        }
        public Builder tableType(@Nullable String tableType) {
            this.tableType = Codegen.ofNullable(tableType);
            return this;
        }
        public Builder targetTable(@Nullable Output<CatalogTableTargetTableGetArgs> targetTable) {
            this.targetTable = targetTable;
            return this;
        }
        public Builder targetTable(@Nullable CatalogTableTargetTableGetArgs targetTable) {
            this.targetTable = Codegen.ofNullable(targetTable);
            return this;
        }
        public Builder viewExpandedText(@Nullable Output<String> viewExpandedText) {
            this.viewExpandedText = viewExpandedText;
            return this;
        }
        public Builder viewExpandedText(@Nullable String viewExpandedText) {
            this.viewExpandedText = Codegen.ofNullable(viewExpandedText);
            return this;
        }
        public Builder viewOriginalText(@Nullable Output<String> viewOriginalText) {
            this.viewOriginalText = viewOriginalText;
            return this;
        }
        public Builder viewOriginalText(@Nullable String viewOriginalText) {
            this.viewOriginalText = Codegen.ofNullable(viewOriginalText);
            return this;
        }        public CatalogTableState build() {
            return new CatalogTableState(arn, catalogId, databaseName, description, name, owner, parameters, partitionIndices, partitionKeys, retention, storageDescriptor, tableType, targetTable, viewExpandedText, viewOriginalText);
        }
    }
}
