// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.googlenative.retail_v2alpha.inputs;

import io.pulumi.core.internal.annotations.InputImport;
import io.pulumi.googlenative.retail_v2alpha.inputs.GoogleCloudRetailV2alphaPriceInfoPriceRangeResponse;
import java.lang.Double;
import java.lang.String;
import java.util.Objects;


public final class GoogleCloudRetailV2alphaPriceInfoResponse extends io.pulumi.resources.InvokeArgs {

    public static final GoogleCloudRetailV2alphaPriceInfoResponse Empty = new GoogleCloudRetailV2alphaPriceInfoResponse();

    @InputImport(name="cost", required=true)
    private final Double cost;

    public Double getCost() {
        return this.cost;
    }

    @InputImport(name="currencyCode", required=true)
    private final String currencyCode;

    public String getCurrencyCode() {
        return this.currencyCode;
    }

    @InputImport(name="originalPrice", required=true)
    private final Double originalPrice;

    public Double getOriginalPrice() {
        return this.originalPrice;
    }

    @InputImport(name="price", required=true)
    private final Double price;

    public Double getPrice() {
        return this.price;
    }

    @InputImport(name="priceEffectiveTime", required=true)
    private final String priceEffectiveTime;

    public String getPriceEffectiveTime() {
        return this.priceEffectiveTime;
    }

    @InputImport(name="priceExpireTime", required=true)
    private final String priceExpireTime;

    public String getPriceExpireTime() {
        return this.priceExpireTime;
    }

    @InputImport(name="priceRange", required=true)
    private final GoogleCloudRetailV2alphaPriceInfoPriceRangeResponse priceRange;

    public GoogleCloudRetailV2alphaPriceInfoPriceRangeResponse getPriceRange() {
        return this.priceRange;
    }

    public GoogleCloudRetailV2alphaPriceInfoResponse(
        Double cost,
        String currencyCode,
        Double originalPrice,
        Double price,
        String priceEffectiveTime,
        String priceExpireTime,
        GoogleCloudRetailV2alphaPriceInfoPriceRangeResponse priceRange) {
        this.cost = Objects.requireNonNull(cost, "expected parameter 'cost' to be non-null");
        this.currencyCode = Objects.requireNonNull(currencyCode, "expected parameter 'currencyCode' to be non-null");
        this.originalPrice = Objects.requireNonNull(originalPrice, "expected parameter 'originalPrice' to be non-null");
        this.price = Objects.requireNonNull(price, "expected parameter 'price' to be non-null");
        this.priceEffectiveTime = Objects.requireNonNull(priceEffectiveTime, "expected parameter 'priceEffectiveTime' to be non-null");
        this.priceExpireTime = Objects.requireNonNull(priceExpireTime, "expected parameter 'priceExpireTime' to be non-null");
        this.priceRange = Objects.requireNonNull(priceRange, "expected parameter 'priceRange' to be non-null");
    }

    private GoogleCloudRetailV2alphaPriceInfoResponse() {
        this.cost = null;
        this.currencyCode = null;
        this.originalPrice = null;
        this.price = null;
        this.priceEffectiveTime = null;
        this.priceExpireTime = null;
        this.priceRange = null;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GoogleCloudRetailV2alphaPriceInfoResponse defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private Double cost;
        private String currencyCode;
        private Double originalPrice;
        private Double price;
        private String priceEffectiveTime;
        private String priceExpireTime;
        private GoogleCloudRetailV2alphaPriceInfoPriceRangeResponse priceRange;

        public Builder() {
    	      // Empty
        }

        public Builder(GoogleCloudRetailV2alphaPriceInfoResponse defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.cost = defaults.cost;
    	      this.currencyCode = defaults.currencyCode;
    	      this.originalPrice = defaults.originalPrice;
    	      this.price = defaults.price;
    	      this.priceEffectiveTime = defaults.priceEffectiveTime;
    	      this.priceExpireTime = defaults.priceExpireTime;
    	      this.priceRange = defaults.priceRange;
        }

        public Builder setCost(Double cost) {
            this.cost = Objects.requireNonNull(cost);
            return this;
        }

        public Builder setCurrencyCode(String currencyCode) {
            this.currencyCode = Objects.requireNonNull(currencyCode);
            return this;
        }

        public Builder setOriginalPrice(Double originalPrice) {
            this.originalPrice = Objects.requireNonNull(originalPrice);
            return this;
        }

        public Builder setPrice(Double price) {
            this.price = Objects.requireNonNull(price);
            return this;
        }

        public Builder setPriceEffectiveTime(String priceEffectiveTime) {
            this.priceEffectiveTime = Objects.requireNonNull(priceEffectiveTime);
            return this;
        }

        public Builder setPriceExpireTime(String priceExpireTime) {
            this.priceExpireTime = Objects.requireNonNull(priceExpireTime);
            return this;
        }

        public Builder setPriceRange(GoogleCloudRetailV2alphaPriceInfoPriceRangeResponse priceRange) {
            this.priceRange = Objects.requireNonNull(priceRange);
            return this;
        }

        public GoogleCloudRetailV2alphaPriceInfoResponse build() {
            return new GoogleCloudRetailV2alphaPriceInfoResponse(cost, currencyCode, originalPrice, price, priceEffectiveTime, priceExpireTime, priceRange);
        }
    }
}
