// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.aws.route53recoveryreadiness.inputs;

import io.pulumi.aws.route53recoveryreadiness.inputs.ResourceSetResourceDnsTargetResourceTargetResourceGetArgs;
import io.pulumi.core.Input;
import io.pulumi.core.annotations.InputImport;
import java.lang.String;
import java.util.Objects;
import javax.annotation.Nullable;


public final class ResourceSetResourceDnsTargetResourceGetArgs extends io.pulumi.resources.ResourceArgs {

    public static final ResourceSetResourceDnsTargetResourceGetArgs Empty = new ResourceSetResourceDnsTargetResourceGetArgs();

    /**
     * Domain name that is targeted.
     * 
     */
    @InputImport(name="domainName", required=true)
      private final Input<String> domainName;

    public Input<String> getDomainName() {
        return this.domainName;
    }

    /**
     * Hosted Zone ARN that contains the DNS record with the provided name of target resource.
     * 
     */
    @InputImport(name="hostedZoneArn")
      private final @Nullable Input<String> hostedZoneArn;

    public Input<String> getHostedZoneArn() {
        return this.hostedZoneArn == null ? Input.empty() : this.hostedZoneArn;
    }

    /**
     * Resource record set ID that is targeted.
     * 
     */
    @InputImport(name="recordSetId")
      private final @Nullable Input<String> recordSetId;

    public Input<String> getRecordSetId() {
        return this.recordSetId == null ? Input.empty() : this.recordSetId;
    }

    /**
     * Type of DNS Record of target resource.
     * 
     */
    @InputImport(name="recordType")
      private final @Nullable Input<String> recordType;

    public Input<String> getRecordType() {
        return this.recordType == null ? Input.empty() : this.recordType;
    }

    /**
     * Target resource the R53 record specified with the above params points to.
     * 
     */
    @InputImport(name="targetResource")
      private final @Nullable Input<ResourceSetResourceDnsTargetResourceTargetResourceGetArgs> targetResource;

    public Input<ResourceSetResourceDnsTargetResourceTargetResourceGetArgs> getTargetResource() {
        return this.targetResource == null ? Input.empty() : this.targetResource;
    }

    public ResourceSetResourceDnsTargetResourceGetArgs(
        Input<String> domainName,
        @Nullable Input<String> hostedZoneArn,
        @Nullable Input<String> recordSetId,
        @Nullable Input<String> recordType,
        @Nullable Input<ResourceSetResourceDnsTargetResourceTargetResourceGetArgs> targetResource) {
        this.domainName = Objects.requireNonNull(domainName, "expected parameter 'domainName' to be non-null");
        this.hostedZoneArn = hostedZoneArn;
        this.recordSetId = recordSetId;
        this.recordType = recordType;
        this.targetResource = targetResource;
    }

    private ResourceSetResourceDnsTargetResourceGetArgs() {
        this.domainName = Input.empty();
        this.hostedZoneArn = Input.empty();
        this.recordSetId = Input.empty();
        this.recordType = Input.empty();
        this.targetResource = Input.empty();
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ResourceSetResourceDnsTargetResourceGetArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private Input<String> domainName;
        private @Nullable Input<String> hostedZoneArn;
        private @Nullable Input<String> recordSetId;
        private @Nullable Input<String> recordType;
        private @Nullable Input<ResourceSetResourceDnsTargetResourceTargetResourceGetArgs> targetResource;

        public Builder() {
    	      // Empty
        }

        public Builder(ResourceSetResourceDnsTargetResourceGetArgs defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.domainName = defaults.domainName;
    	      this.hostedZoneArn = defaults.hostedZoneArn;
    	      this.recordSetId = defaults.recordSetId;
    	      this.recordType = defaults.recordType;
    	      this.targetResource = defaults.targetResource;
        }

        public Builder domainName(Input<String> domainName) {
            this.domainName = Objects.requireNonNull(domainName);
            return this;
        }

        public Builder domainName(String domainName) {
            this.domainName = Input.of(Objects.requireNonNull(domainName));
            return this;
        }

        public Builder hostedZoneArn(@Nullable Input<String> hostedZoneArn) {
            this.hostedZoneArn = hostedZoneArn;
            return this;
        }

        public Builder hostedZoneArn(@Nullable String hostedZoneArn) {
            this.hostedZoneArn = Input.ofNullable(hostedZoneArn);
            return this;
        }

        public Builder recordSetId(@Nullable Input<String> recordSetId) {
            this.recordSetId = recordSetId;
            return this;
        }

        public Builder recordSetId(@Nullable String recordSetId) {
            this.recordSetId = Input.ofNullable(recordSetId);
            return this;
        }

        public Builder recordType(@Nullable Input<String> recordType) {
            this.recordType = recordType;
            return this;
        }

        public Builder recordType(@Nullable String recordType) {
            this.recordType = Input.ofNullable(recordType);
            return this;
        }

        public Builder targetResource(@Nullable Input<ResourceSetResourceDnsTargetResourceTargetResourceGetArgs> targetResource) {
            this.targetResource = targetResource;
            return this;
        }

        public Builder targetResource(@Nullable ResourceSetResourceDnsTargetResourceTargetResourceGetArgs targetResource) {
            this.targetResource = Input.ofNullable(targetResource);
            return this;
        }
        public ResourceSetResourceDnsTargetResourceGetArgs build() {
            return new ResourceSetResourceDnsTargetResourceGetArgs(domainName, hostedZoneArn, recordSetId, recordType, targetResource);
        }
    }
}
