# Docs: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "impact/no-changelog-required"

  # Maintain dependencies for gradle
  - package-ecosystem: "gradle"
    directory: "/sdk/java"
    schedule:
      interval: "daily"
    labels:
      - "impact/no-changelog-required"

  # Maintain dependencies for gomod
  - package-ecosystem: "gomod"
    directory: "/pkg"
    schedule:
      interval: "daily"
    labels:
      - "impact/no-changelog-required"