run:
  timeout: 10m
linters:
  enable-all: false
  enable:
    - errcheck
    - goconst
    - gofumpt
    - revive
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - unconvert

issues:
  exclude:
    # https://github.com/pulumi/pulumi/issues/9469
    - 'Name is deprecated: Name returns the variable or declaration name of the resource'

    # https://github.com/pulumi/pulumi/issues/11870
    - 'strings.Title has been deprecated'