version: "2"
linters:
  enable:
    - goconst
    - gosec
    - lll
    - misspell
    - nakedret
    - revive
    - unconvert
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      # https://github.com/pulumi/pulumi/issues/9469
      - path: (.+)\.go$
        text: 'Name is deprecated: Name returns the variable or declaration name of the resource'
      # https://github.com/pulumi/pulumi/issues/11870
      - path: (.+)\.go$
        text: strings.Title has been deprecated
      - linters:
          - staticcheck
        text: 'error strings should not be capitalized'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
