// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.aws.s3.inputs;

import io.pulumi.aws.s3.inputs.BucketServerSideEncryptionConfigurationRuleApplyServerSideEncryptionByDefaultArgs;
import io.pulumi.core.Input;
import io.pulumi.core.annotations.InputImport;
import java.lang.Boolean;
import java.util.Objects;
import javax.annotation.Nullable;


public final class BucketServerSideEncryptionConfigurationRuleArgs extends io.pulumi.resources.ResourceArgs {

    public static final BucketServerSideEncryptionConfigurationRuleArgs Empty = new BucketServerSideEncryptionConfigurationRuleArgs();

    /**
     * A single object for setting server-side encryption by default. (documented below)
     * 
     */
    @InputImport(name="applyServerSideEncryptionByDefault", required=true)
      private final Input<BucketServerSideEncryptionConfigurationRuleApplyServerSideEncryptionByDefaultArgs> applyServerSideEncryptionByDefault;

    public Input<BucketServerSideEncryptionConfigurationRuleApplyServerSideEncryptionByDefaultArgs> getApplyServerSideEncryptionByDefault() {
        return this.applyServerSideEncryptionByDefault;
    }

    /**
     * Whether or not to use [Amazon S3 Bucket Keys](https://docs.aws.amazon.com/AmazonS3/latest/dev/bucket-key.html) for SSE-KMS.
     * 
     */
    @InputImport(name="bucketKeyEnabled")
      private final @Nullable Input<Boolean> bucketKeyEnabled;

    public Input<Boolean> getBucketKeyEnabled() {
        return this.bucketKeyEnabled == null ? Input.empty() : this.bucketKeyEnabled;
    }

    public BucketServerSideEncryptionConfigurationRuleArgs(
        Input<BucketServerSideEncryptionConfigurationRuleApplyServerSideEncryptionByDefaultArgs> applyServerSideEncryptionByDefault,
        @Nullable Input<Boolean> bucketKeyEnabled) {
        this.applyServerSideEncryptionByDefault = Objects.requireNonNull(applyServerSideEncryptionByDefault, "expected parameter 'applyServerSideEncryptionByDefault' to be non-null");
        this.bucketKeyEnabled = bucketKeyEnabled;
    }

    private BucketServerSideEncryptionConfigurationRuleArgs() {
        this.applyServerSideEncryptionByDefault = Input.empty();
        this.bucketKeyEnabled = Input.empty();
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(BucketServerSideEncryptionConfigurationRuleArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private Input<BucketServerSideEncryptionConfigurationRuleApplyServerSideEncryptionByDefaultArgs> applyServerSideEncryptionByDefault;
        private @Nullable Input<Boolean> bucketKeyEnabled;

        public Builder() {
    	      // Empty
        }

        public Builder(BucketServerSideEncryptionConfigurationRuleArgs defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.applyServerSideEncryptionByDefault = defaults.applyServerSideEncryptionByDefault;
    	      this.bucketKeyEnabled = defaults.bucketKeyEnabled;
        }

        public Builder setApplyServerSideEncryptionByDefault(Input<BucketServerSideEncryptionConfigurationRuleApplyServerSideEncryptionByDefaultArgs> applyServerSideEncryptionByDefault) {
            this.applyServerSideEncryptionByDefault = Objects.requireNonNull(applyServerSideEncryptionByDefault);
            return this;
        }

        public Builder setApplyServerSideEncryptionByDefault(BucketServerSideEncryptionConfigurationRuleApplyServerSideEncryptionByDefaultArgs applyServerSideEncryptionByDefault) {
            this.applyServerSideEncryptionByDefault = Input.of(Objects.requireNonNull(applyServerSideEncryptionByDefault));
            return this;
        }

        public Builder setBucketKeyEnabled(@Nullable Input<Boolean> bucketKeyEnabled) {
            this.bucketKeyEnabled = bucketKeyEnabled;
            return this;
        }

        public Builder setBucketKeyEnabled(@Nullable Boolean bucketKeyEnabled) {
            this.bucketKeyEnabled = Input.ofNullable(bucketKeyEnabled);
            return this;
        }
        public BucketServerSideEncryptionConfigurationRuleArgs build() {
            return new BucketServerSideEncryptionConfigurationRuleArgs(applyServerSideEncryptionByDefault, bucketKeyEnabled);
        }
    }
}
