// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.azurenative.media;

import com.pulumi.azurenative.media.inputs.TransformOutputArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.core.internal.Codegen;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import javax.annotation.Nullable;


public final class TransformArgs extends com.pulumi.resources.ResourceArgs {

    public static final TransformArgs Empty = new TransformArgs();

    /**
     * The Media Services account name.
     * 
     */
    @Import(name="accountName", required=true)
      private final Output<String> accountName;

    public Output<String> getAccountName() {
        return this.accountName;
    }

    /**
     * An optional verbose description of the Transform.
     * 
     */
    @Import(name="description")
      private final @Nullable Output<String> description;

    public Output<String> getDescription() {
        return this.description == null ? Codegen.empty() : this.description;
    }

    /**
     * An array of one or more TransformOutputs that the Transform should generate.
     * 
     */
    @Import(name="outputs", required=true)
      private final Output<List<TransformOutputArgs>> outputs;

    public Output<List<TransformOutputArgs>> getOutputs() {
        return this.outputs;
    }

    /**
     * The name of the resource group within the Azure subscription.
     * 
     */
    @Import(name="resourceGroupName", required=true)
      private final Output<String> resourceGroupName;

    public Output<String> getResourceGroupName() {
        return this.resourceGroupName;
    }

    /**
     * The Transform name.
     * 
     */
    @Import(name="transformName")
      private final @Nullable Output<String> transformName;

    public Output<String> getTransformName() {
        return this.transformName == null ? Codegen.empty() : this.transformName;
    }

    public TransformArgs(
        Output<String> accountName,
        @Nullable Output<String> description,
        Output<List<TransformOutputArgs>> outputs,
        Output<String> resourceGroupName,
        @Nullable Output<String> transformName) {
        this.accountName = Objects.requireNonNull(accountName, "expected parameter 'accountName' to be non-null");
        this.description = description;
        this.outputs = Objects.requireNonNull(outputs, "expected parameter 'outputs' to be non-null");
        this.resourceGroupName = Objects.requireNonNull(resourceGroupName, "expected parameter 'resourceGroupName' to be non-null");
        this.transformName = transformName;
    }

    private TransformArgs() {
        this.accountName = Codegen.empty();
        this.description = Codegen.empty();
        this.outputs = Codegen.empty();
        this.resourceGroupName = Codegen.empty();
        this.transformName = Codegen.empty();
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(TransformArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private Output<String> accountName;
        private @Nullable Output<String> description;
        private Output<List<TransformOutputArgs>> outputs;
        private Output<String> resourceGroupName;
        private @Nullable Output<String> transformName;

        public Builder() {
    	      // Empty
        }

        public Builder(TransformArgs defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.accountName = defaults.accountName;
    	      this.description = defaults.description;
    	      this.outputs = defaults.outputs;
    	      this.resourceGroupName = defaults.resourceGroupName;
    	      this.transformName = defaults.transformName;
        }

        public Builder accountName(Output<String> accountName) {
            this.accountName = Objects.requireNonNull(accountName);
            return this;
        }
        public Builder accountName(String accountName) {
            this.accountName = Output.of(Objects.requireNonNull(accountName));
            return this;
        }
        public Builder description(@Nullable Output<String> description) {
            this.description = description;
            return this;
        }
        public Builder description(@Nullable String description) {
            this.description = Codegen.ofNullable(description);
            return this;
        }
        public Builder outputs(Output<List<TransformOutputArgs>> outputs) {
            this.outputs = Objects.requireNonNull(outputs);
            return this;
        }
        public Builder outputs(List<TransformOutputArgs> outputs) {
            this.outputs = Output.of(Objects.requireNonNull(outputs));
            return this;
        }
        public Builder outputs(TransformOutputArgs... outputs) {
            return outputs(List.of(outputs));
        }
        public Builder resourceGroupName(Output<String> resourceGroupName) {
            this.resourceGroupName = Objects.requireNonNull(resourceGroupName);
            return this;
        }
        public Builder resourceGroupName(String resourceGroupName) {
            this.resourceGroupName = Output.of(Objects.requireNonNull(resourceGroupName));
            return this;
        }
        public Builder transformName(@Nullable Output<String> transformName) {
            this.transformName = transformName;
            return this;
        }
        public Builder transformName(@Nullable String transformName) {
            this.transformName = Codegen.ofNullable(transformName);
            return this;
        }        public TransformArgs build() {
            return new TransformArgs(accountName, description, outputs, resourceGroupName, transformName);
        }
    }
}
