// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.azurenative.recoveryservices.inputs;

import com.pulumi.azurenative.recoveryservices.inputs.A2AVmDiskInputDetailsArgs;
import com.pulumi.azurenative.recoveryservices.inputs.A2AVmManagedDiskInputDetailsArgs;
import com.pulumi.azurenative.recoveryservices.inputs.DiskEncryptionInfoArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.core.internal.Codegen;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


/**
 * A2A enable protection input.
 * 
 */
public final class A2AEnableProtectionInputArgs extends com.pulumi.resources.ResourceArgs {

    public static final A2AEnableProtectionInputArgs Empty = new A2AEnableProtectionInputArgs();

    /**
     * The recovery disk encryption information.
     * 
     */
    @Import(name="diskEncryptionInfo")
    private @Nullable Output<DiskEncryptionInfoArgs> diskEncryptionInfo;

    public Optional<Output<DiskEncryptionInfoArgs>> diskEncryptionInfo() {
        return Optional.ofNullable(this.diskEncryptionInfo);
    }

    /**
     * The fabric specific object Id of the virtual machine.
     * 
     */
    @Import(name="fabricObjectId")
    private @Nullable Output<String> fabricObjectId;

    public Optional<Output<String>> fabricObjectId() {
        return Optional.ofNullable(this.fabricObjectId);
    }

    /**
     * The class type.
     * Expected value is &#39;A2A&#39;.
     * 
     */
    @Import(name="instanceType")
    private @Nullable Output<String> instanceType;

    public Optional<Output<String>> instanceType() {
        return Optional.ofNullable(this.instanceType);
    }

    /**
     * The multi vm group name.
     * 
     */
    @Import(name="multiVmGroupName")
    private @Nullable Output<String> multiVmGroupName;

    public Optional<Output<String>> multiVmGroupName() {
        return Optional.ofNullable(this.multiVmGroupName);
    }

    /**
     * The recovery availability set Id.
     * 
     */
    @Import(name="recoveryAvailabilitySetId")
    private @Nullable Output<String> recoveryAvailabilitySetId;

    public Optional<Output<String>> recoveryAvailabilitySetId() {
        return Optional.ofNullable(this.recoveryAvailabilitySetId);
    }

    /**
     * The recovery availability zone.
     * 
     */
    @Import(name="recoveryAvailabilityZone")
    private @Nullable Output<String> recoveryAvailabilityZone;

    public Optional<Output<String>> recoveryAvailabilityZone() {
        return Optional.ofNullable(this.recoveryAvailabilityZone);
    }

    /**
     * The recovery Azure virtual network ARM id.
     * 
     */
    @Import(name="recoveryAzureNetworkId")
    private @Nullable Output<String> recoveryAzureNetworkId;

    public Optional<Output<String>> recoveryAzureNetworkId() {
        return Optional.ofNullable(this.recoveryAzureNetworkId);
    }

    /**
     * The boot diagnostic storage account.
     * 
     */
    @Import(name="recoveryBootDiagStorageAccountId")
    private @Nullable Output<String> recoveryBootDiagStorageAccountId;

    public Optional<Output<String>> recoveryBootDiagStorageAccountId() {
        return Optional.ofNullable(this.recoveryBootDiagStorageAccountId);
    }

    /**
     * The recovery cloud service Id. Valid for V1 scenarios.
     * 
     */
    @Import(name="recoveryCloudServiceId")
    private @Nullable Output<String> recoveryCloudServiceId;

    public Optional<Output<String>> recoveryCloudServiceId() {
        return Optional.ofNullable(this.recoveryCloudServiceId);
    }

    /**
     * The recovery container Id.
     * 
     */
    @Import(name="recoveryContainerId")
    private @Nullable Output<String> recoveryContainerId;

    public Optional<Output<String>> recoveryContainerId() {
        return Optional.ofNullable(this.recoveryContainerId);
    }

    /**
     * The recovery proximity placement group Id.
     * 
     */
    @Import(name="recoveryProximityPlacementGroupId")
    private @Nullable Output<String> recoveryProximityPlacementGroupId;

    public Optional<Output<String>> recoveryProximityPlacementGroupId() {
        return Optional.ofNullable(this.recoveryProximityPlacementGroupId);
    }

    /**
     * The recovery resource group Id. Valid for V2 scenarios.
     * 
     */
    @Import(name="recoveryResourceGroupId")
    private @Nullable Output<String> recoveryResourceGroupId;

    public Optional<Output<String>> recoveryResourceGroupId() {
        return Optional.ofNullable(this.recoveryResourceGroupId);
    }

    /**
     * The recovery subnet name.
     * 
     */
    @Import(name="recoverySubnetName")
    private @Nullable Output<String> recoverySubnetName;

    public Optional<Output<String>> recoverySubnetName() {
        return Optional.ofNullable(this.recoverySubnetName);
    }

    /**
     * The list of vm disk details.
     * 
     */
    @Import(name="vmDisks")
    private @Nullable Output<List<A2AVmDiskInputDetailsArgs>> vmDisks;

    public Optional<Output<List<A2AVmDiskInputDetailsArgs>>> vmDisks() {
        return Optional.ofNullable(this.vmDisks);
    }

    /**
     * The list of vm managed disk details.
     * 
     */
    @Import(name="vmManagedDisks")
    private @Nullable Output<List<A2AVmManagedDiskInputDetailsArgs>> vmManagedDisks;

    public Optional<Output<List<A2AVmManagedDiskInputDetailsArgs>>> vmManagedDisks() {
        return Optional.ofNullable(this.vmManagedDisks);
    }

    private A2AEnableProtectionInputArgs() {}

    private A2AEnableProtectionInputArgs(A2AEnableProtectionInputArgs $) {
        this.diskEncryptionInfo = $.diskEncryptionInfo;
        this.fabricObjectId = $.fabricObjectId;
        this.instanceType = $.instanceType;
        this.multiVmGroupName = $.multiVmGroupName;
        this.recoveryAvailabilitySetId = $.recoveryAvailabilitySetId;
        this.recoveryAvailabilityZone = $.recoveryAvailabilityZone;
        this.recoveryAzureNetworkId = $.recoveryAzureNetworkId;
        this.recoveryBootDiagStorageAccountId = $.recoveryBootDiagStorageAccountId;
        this.recoveryCloudServiceId = $.recoveryCloudServiceId;
        this.recoveryContainerId = $.recoveryContainerId;
        this.recoveryProximityPlacementGroupId = $.recoveryProximityPlacementGroupId;
        this.recoveryResourceGroupId = $.recoveryResourceGroupId;
        this.recoverySubnetName = $.recoverySubnetName;
        this.vmDisks = $.vmDisks;
        this.vmManagedDisks = $.vmManagedDisks;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(A2AEnableProtectionInputArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private A2AEnableProtectionInputArgs $;

        public Builder() {
            $ = new A2AEnableProtectionInputArgs();
        }

        public Builder(A2AEnableProtectionInputArgs defaults) {
            $ = new A2AEnableProtectionInputArgs(Objects.requireNonNull(defaults));
        }

        public Builder diskEncryptionInfo(@Nullable Output<DiskEncryptionInfoArgs> diskEncryptionInfo) {
            $.diskEncryptionInfo = diskEncryptionInfo;
            return this;
        }

        public Builder diskEncryptionInfo(DiskEncryptionInfoArgs diskEncryptionInfo) {
            return diskEncryptionInfo(Output.of(diskEncryptionInfo));
        }

        public Builder fabricObjectId(@Nullable Output<String> fabricObjectId) {
            $.fabricObjectId = fabricObjectId;
            return this;
        }

        public Builder fabricObjectId(String fabricObjectId) {
            return fabricObjectId(Output.of(fabricObjectId));
        }

        public Builder instanceType(@Nullable Output<String> instanceType) {
            $.instanceType = instanceType;
            return this;
        }

        public Builder instanceType(String instanceType) {
            return instanceType(Output.of(instanceType));
        }

        public Builder multiVmGroupName(@Nullable Output<String> multiVmGroupName) {
            $.multiVmGroupName = multiVmGroupName;
            return this;
        }

        public Builder multiVmGroupName(String multiVmGroupName) {
            return multiVmGroupName(Output.of(multiVmGroupName));
        }

        public Builder recoveryAvailabilitySetId(@Nullable Output<String> recoveryAvailabilitySetId) {
            $.recoveryAvailabilitySetId = recoveryAvailabilitySetId;
            return this;
        }

        public Builder recoveryAvailabilitySetId(String recoveryAvailabilitySetId) {
            return recoveryAvailabilitySetId(Output.of(recoveryAvailabilitySetId));
        }

        public Builder recoveryAvailabilityZone(@Nullable Output<String> recoveryAvailabilityZone) {
            $.recoveryAvailabilityZone = recoveryAvailabilityZone;
            return this;
        }

        public Builder recoveryAvailabilityZone(String recoveryAvailabilityZone) {
            return recoveryAvailabilityZone(Output.of(recoveryAvailabilityZone));
        }

        public Builder recoveryAzureNetworkId(@Nullable Output<String> recoveryAzureNetworkId) {
            $.recoveryAzureNetworkId = recoveryAzureNetworkId;
            return this;
        }

        public Builder recoveryAzureNetworkId(String recoveryAzureNetworkId) {
            return recoveryAzureNetworkId(Output.of(recoveryAzureNetworkId));
        }

        public Builder recoveryBootDiagStorageAccountId(@Nullable Output<String> recoveryBootDiagStorageAccountId) {
            $.recoveryBootDiagStorageAccountId = recoveryBootDiagStorageAccountId;
            return this;
        }

        public Builder recoveryBootDiagStorageAccountId(String recoveryBootDiagStorageAccountId) {
            return recoveryBootDiagStorageAccountId(Output.of(recoveryBootDiagStorageAccountId));
        }

        public Builder recoveryCloudServiceId(@Nullable Output<String> recoveryCloudServiceId) {
            $.recoveryCloudServiceId = recoveryCloudServiceId;
            return this;
        }

        public Builder recoveryCloudServiceId(String recoveryCloudServiceId) {
            return recoveryCloudServiceId(Output.of(recoveryCloudServiceId));
        }

        public Builder recoveryContainerId(@Nullable Output<String> recoveryContainerId) {
            $.recoveryContainerId = recoveryContainerId;
            return this;
        }

        public Builder recoveryContainerId(String recoveryContainerId) {
            return recoveryContainerId(Output.of(recoveryContainerId));
        }

        public Builder recoveryProximityPlacementGroupId(@Nullable Output<String> recoveryProximityPlacementGroupId) {
            $.recoveryProximityPlacementGroupId = recoveryProximityPlacementGroupId;
            return this;
        }

        public Builder recoveryProximityPlacementGroupId(String recoveryProximityPlacementGroupId) {
            return recoveryProximityPlacementGroupId(Output.of(recoveryProximityPlacementGroupId));
        }

        public Builder recoveryResourceGroupId(@Nullable Output<String> recoveryResourceGroupId) {
            $.recoveryResourceGroupId = recoveryResourceGroupId;
            return this;
        }

        public Builder recoveryResourceGroupId(String recoveryResourceGroupId) {
            return recoveryResourceGroupId(Output.of(recoveryResourceGroupId));
        }

        public Builder recoverySubnetName(@Nullable Output<String> recoverySubnetName) {
            $.recoverySubnetName = recoverySubnetName;
            return this;
        }

        public Builder recoverySubnetName(String recoverySubnetName) {
            return recoverySubnetName(Output.of(recoverySubnetName));
        }

        public Builder vmDisks(@Nullable Output<List<A2AVmDiskInputDetailsArgs>> vmDisks) {
            $.vmDisks = vmDisks;
            return this;
        }

        public Builder vmDisks(List<A2AVmDiskInputDetailsArgs> vmDisks) {
            return vmDisks(Output.of(vmDisks));
        }

        public Builder vmDisks(A2AVmDiskInputDetailsArgs... vmDisks) {
            return vmDisks(List.of(vmDisks));
        }

        public Builder vmManagedDisks(@Nullable Output<List<A2AVmManagedDiskInputDetailsArgs>> vmManagedDisks) {
            $.vmManagedDisks = vmManagedDisks;
            return this;
        }

        public Builder vmManagedDisks(List<A2AVmManagedDiskInputDetailsArgs> vmManagedDisks) {
            return vmManagedDisks(Output.of(vmManagedDisks));
        }

        public Builder vmManagedDisks(A2AVmManagedDiskInputDetailsArgs... vmManagedDisks) {
            return vmManagedDisks(List.of(vmManagedDisks));
        }

        public A2AEnableProtectionInputArgs build() {
            $.instanceType = Codegen.stringProp("instanceType").output().arg($.instanceType).getNullable();
            return $;
        }
    }

}
