// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.aws;

import io.pulumi.aws.Utilities;
import io.pulumi.core.internal.Optionals;
import java.lang.String;

public final class Config {

    private static final io.pulumi.Config config = io.pulumi.Config.of("aws");
/**
 * The region where AWS operations will take place. Examples are us-east-1, us-west-2, etc.
 * 
 */
    public String region() {
        return Optionals.combine(config.get("region"), Utilities.getEnv("AWS_REGION", "AWS_DEFAULT_REGION").orElse(null));
    }
}
