// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.googlenative.privateca_v1beta1.inputs;

import io.pulumi.core.internal.annotations.InputImport;
import java.lang.Boolean;
import java.lang.Integer;
import java.util.Objects;


public final class CaOptionsResponse extends io.pulumi.resources.InvokeArgs {

    public static final CaOptionsResponse Empty = new CaOptionsResponse();

    @InputImport(name="isCa", required=true)
    private final Boolean isCa;

    public Boolean getIsCa() {
        return this.isCa;
    }

    @InputImport(name="maxIssuerPathLength", required=true)
    private final Integer maxIssuerPathLength;

    public Integer getMaxIssuerPathLength() {
        return this.maxIssuerPathLength;
    }

    public CaOptionsResponse(
        Boolean isCa,
        Integer maxIssuerPathLength) {
        this.isCa = Objects.requireNonNull(isCa, "expected parameter 'isCa' to be non-null");
        this.maxIssuerPathLength = Objects.requireNonNull(maxIssuerPathLength, "expected parameter 'maxIssuerPathLength' to be non-null");
    }

    private CaOptionsResponse() {
        this.isCa = null;
        this.maxIssuerPathLength = null;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(CaOptionsResponse defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private Boolean isCa;
        private Integer maxIssuerPathLength;

        public Builder() {
    	      // Empty
        }

        public Builder(CaOptionsResponse defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.isCa = defaults.isCa;
    	      this.maxIssuerPathLength = defaults.maxIssuerPathLength;
        }

        public Builder setIsCa(Boolean isCa) {
            this.isCa = Objects.requireNonNull(isCa);
            return this;
        }

        public Builder setMaxIssuerPathLength(Integer maxIssuerPathLength) {
            this.maxIssuerPathLength = Objects.requireNonNull(maxIssuerPathLength);
            return this;
        }

        public CaOptionsResponse build() {
            return new CaOptionsResponse(isCa, maxIssuerPathLength);
        }
    }
}
