// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.awsnative.ec2.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;


public final class SpotFleetGroupIdentifier extends com.pulumi.resources.InvokeArgs {

    public static final SpotFleetGroupIdentifier Empty = new SpotFleetGroupIdentifier();

    @Import(name="groupId", required=true)
    private String groupId;

    public String groupId() {
        return this.groupId;
    }

    private SpotFleetGroupIdentifier() {}

    private SpotFleetGroupIdentifier(SpotFleetGroupIdentifier $) {
        this.groupId = $.groupId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SpotFleetGroupIdentifier defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SpotFleetGroupIdentifier $;

        public Builder() {
            $ = new SpotFleetGroupIdentifier();
        }

        public Builder(SpotFleetGroupIdentifier defaults) {
            $ = new SpotFleetGroupIdentifier(Objects.requireNonNull(defaults));
        }

        public Builder groupId(String groupId) {
            $.groupId = groupId;
            return this;
        }

        public SpotFleetGroupIdentifier build() {
            $.groupId = Objects.requireNonNull($.groupId, "expected parameter 'groupId' to be non-null");
            return $;
        }
    }

}
