// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.azurenative.compute.outputs;

import io.pulumi.azurenative.compute.outputs.DedicatedHostInstanceViewWithNameResponse;
import io.pulumi.core.annotations.OutputCustomType;
import java.util.List;
import java.util.Objects;
import javax.annotation.Nullable;

@OutputCustomType
public final class DedicatedHostGroupInstanceViewResponse {
    /**
     * List of instance view of the dedicated hosts under the dedicated host group.
     * 
     */
    private final @Nullable List<DedicatedHostInstanceViewWithNameResponse> hosts;

    @OutputCustomType.Constructor({"hosts"})
    private DedicatedHostGroupInstanceViewResponse(@Nullable List<DedicatedHostInstanceViewWithNameResponse> hosts) {
        this.hosts = hosts;
    }

    /**
     * List of instance view of the dedicated hosts under the dedicated host group.
     * 
    */
    public List<DedicatedHostInstanceViewWithNameResponse> getHosts() {
        return this.hosts == null ? List.of() : this.hosts;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(DedicatedHostGroupInstanceViewResponse defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable List<DedicatedHostInstanceViewWithNameResponse> hosts;

        public Builder() {
    	      // Empty
        }

        public Builder(DedicatedHostGroupInstanceViewResponse defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.hosts = defaults.hosts;
        }

        public Builder setHosts(@Nullable List<DedicatedHostInstanceViewWithNameResponse> hosts) {
            this.hosts = hosts;
            return this;
        }
        public DedicatedHostGroupInstanceViewResponse build() {
            return new DedicatedHostGroupInstanceViewResponse(hosts);
        }
    }
}
