// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.awsnative.cloudfront.inputs;

import io.pulumi.core.Output;
import io.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import javax.annotation.Nullable;


public final class DistributionLambdaFunctionAssociationArgs extends io.pulumi.resources.ResourceArgs {

    public static final DistributionLambdaFunctionAssociationArgs Empty = new DistributionLambdaFunctionAssociationArgs();

    @Import(name="eventType")
      private final @Nullable Output<String> eventType;

    public Output<String> getEventType() {
        return this.eventType == null ? Output.empty() : this.eventType;
    }

    @Import(name="includeBody")
      private final @Nullable Output<Boolean> includeBody;

    public Output<Boolean> getIncludeBody() {
        return this.includeBody == null ? Output.empty() : this.includeBody;
    }

    @Import(name="lambdaFunctionARN")
      private final @Nullable Output<String> lambdaFunctionARN;

    public Output<String> getLambdaFunctionARN() {
        return this.lambdaFunctionARN == null ? Output.empty() : this.lambdaFunctionARN;
    }

    public DistributionLambdaFunctionAssociationArgs(
        @Nullable Output<String> eventType,
        @Nullable Output<Boolean> includeBody,
        @Nullable Output<String> lambdaFunctionARN) {
        this.eventType = eventType;
        this.includeBody = includeBody;
        this.lambdaFunctionARN = lambdaFunctionARN;
    }

    private DistributionLambdaFunctionAssociationArgs() {
        this.eventType = Output.empty();
        this.includeBody = Output.empty();
        this.lambdaFunctionARN = Output.empty();
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(DistributionLambdaFunctionAssociationArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable Output<String> eventType;
        private @Nullable Output<Boolean> includeBody;
        private @Nullable Output<String> lambdaFunctionARN;

        public Builder() {
    	      // Empty
        }

        public Builder(DistributionLambdaFunctionAssociationArgs defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.eventType = defaults.eventType;
    	      this.includeBody = defaults.includeBody;
    	      this.lambdaFunctionARN = defaults.lambdaFunctionARN;
        }

        public Builder eventType(@Nullable Output<String> eventType) {
            this.eventType = eventType;
            return this;
        }
        public Builder eventType(@Nullable String eventType) {
            this.eventType = Output.ofNullable(eventType);
            return this;
        }
        public Builder includeBody(@Nullable Output<Boolean> includeBody) {
            this.includeBody = includeBody;
            return this;
        }
        public Builder includeBody(@Nullable Boolean includeBody) {
            this.includeBody = Output.ofNullable(includeBody);
            return this;
        }
        public Builder lambdaFunctionARN(@Nullable Output<String> lambdaFunctionARN) {
            this.lambdaFunctionARN = lambdaFunctionARN;
            return this;
        }
        public Builder lambdaFunctionARN(@Nullable String lambdaFunctionARN) {
            this.lambdaFunctionARN = Output.ofNullable(lambdaFunctionARN);
            return this;
        }        public DistributionLambdaFunctionAssociationArgs build() {
            return new DistributionLambdaFunctionAssociationArgs(eventType, includeBody, lambdaFunctionARN);
        }
    }
}
