// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.azurenative.containerregistry.inputs;

import io.pulumi.azurenative.containerregistry.inputs.SyncPropertiesResponse;
import io.pulumi.core.internal.annotations.InputImport;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


/**
 * The properties of the connected registry parent.
 * 
 */
public final class ParentPropertiesResponse extends io.pulumi.resources.InvokeArgs {

    public static final ParentPropertiesResponse Empty = new ParentPropertiesResponse();

    /**
     * The resource ID of the parent to which the connected registry will be associated.
     * 
     */
    @InputImport(name="id")
    private final @Nullable String id;

    public Optional<String> getId() {
        return this.id == null ? Optional.empty() : Optional.ofNullable(this.id);
    }

    /**
     * The sync properties of the connected registry with its parent.
     * 
     */
    @InputImport(name="syncProperties", required=true)
    private final SyncPropertiesResponse syncProperties;

    public SyncPropertiesResponse getSyncProperties() {
        return this.syncProperties;
    }

    public ParentPropertiesResponse(
        @Nullable String id,
        SyncPropertiesResponse syncProperties) {
        this.id = id;
        this.syncProperties = Objects.requireNonNull(syncProperties, "expected parameter 'syncProperties' to be non-null");
    }

    private ParentPropertiesResponse() {
        this.id = null;
        this.syncProperties = null;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ParentPropertiesResponse defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable String id;
        private SyncPropertiesResponse syncProperties;

        public Builder() {
    	      // Empty
        }

        public Builder(ParentPropertiesResponse defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.id = defaults.id;
    	      this.syncProperties = defaults.syncProperties;
        }

        public Builder setId(@Nullable String id) {
            this.id = id;
            return this;
        }

        public Builder setSyncProperties(SyncPropertiesResponse syncProperties) {
            this.syncProperties = Objects.requireNonNull(syncProperties);
            return this;
        }

        public ParentPropertiesResponse build() {
            return new ParentPropertiesResponse(id, syncProperties);
        }
    }
}
