// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.oci.DevOps.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetRepositoryObjectContentResult {
    private final @Nullable String filePath;
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private final String id;
    private final String repositoryId;
    private final String sha;

    @CustomType.Constructor
    private GetRepositoryObjectContentResult(
        @CustomType.Parameter("filePath") @Nullable String filePath,
        @CustomType.Parameter("id") String id,
        @CustomType.Parameter("repositoryId") String repositoryId,
        @CustomType.Parameter("sha") String sha) {
        this.filePath = filePath;
        this.id = id;
        this.repositoryId = repositoryId;
        this.sha = sha;
    }

    public Optional<String> filePath() {
        return Optional.ofNullable(this.filePath);
    }
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    public String repositoryId() {
        return this.repositoryId;
    }
    public String sha() {
        return this.sha;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetRepositoryObjectContentResult defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable String filePath;
        private String id;
        private String repositoryId;
        private String sha;

        public Builder() {
    	      // Empty
        }

        public Builder(GetRepositoryObjectContentResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.filePath = defaults.filePath;
    	      this.id = defaults.id;
    	      this.repositoryId = defaults.repositoryId;
    	      this.sha = defaults.sha;
        }

        public Builder filePath(@Nullable String filePath) {
            this.filePath = filePath;
            return this;
        }
        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }
        public Builder repositoryId(String repositoryId) {
            this.repositoryId = Objects.requireNonNull(repositoryId);
            return this;
        }
        public Builder sha(String sha) {
            this.sha = Objects.requireNonNull(sha);
            return this;
        }        public GetRepositoryObjectContentResult build() {
            return new GetRepositoryObjectContentResult(filePath, id, repositoryId, sha);
        }
    }
}
