// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.awsnative.datasync.outputs;

import com.pulumi.awsnative.datasync.outputs.LocationFSxOpenZFSTag;
import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetLocationFSxOpenZFSResult {
    /**
     * @return The Amazon Resource Name (ARN) of the Amazon FSx OpenZFS file system location that is created.
     * 
     */
    private final @Nullable String locationArn;
    /**
     * @return The URL of the FSx OpenZFS that was described.
     * 
     */
    private final @Nullable String locationUri;
    /**
     * @return An array of key-value pairs to apply to this resource.
     * 
     */
    private final @Nullable List<LocationFSxOpenZFSTag> tags;

    @CustomType.Constructor
    private GetLocationFSxOpenZFSResult(
        @CustomType.Parameter("locationArn") @Nullable String locationArn,
        @CustomType.Parameter("locationUri") @Nullable String locationUri,
        @CustomType.Parameter("tags") @Nullable List<LocationFSxOpenZFSTag> tags) {
        this.locationArn = locationArn;
        this.locationUri = locationUri;
        this.tags = tags;
    }

    /**
     * @return The Amazon Resource Name (ARN) of the Amazon FSx OpenZFS file system location that is created.
     * 
     */
    public Optional<String> locationArn() {
        return Optional.ofNullable(this.locationArn);
    }
    /**
     * @return The URL of the FSx OpenZFS that was described.
     * 
     */
    public Optional<String> locationUri() {
        return Optional.ofNullable(this.locationUri);
    }
    /**
     * @return An array of key-value pairs to apply to this resource.
     * 
     */
    public List<LocationFSxOpenZFSTag> tags() {
        return this.tags == null ? List.of() : this.tags;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetLocationFSxOpenZFSResult defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable String locationArn;
        private @Nullable String locationUri;
        private @Nullable List<LocationFSxOpenZFSTag> tags;

        public Builder() {
    	      // Empty
        }

        public Builder(GetLocationFSxOpenZFSResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.locationArn = defaults.locationArn;
    	      this.locationUri = defaults.locationUri;
    	      this.tags = defaults.tags;
        }

        public Builder locationArn(@Nullable String locationArn) {
            this.locationArn = locationArn;
            return this;
        }
        public Builder locationUri(@Nullable String locationUri) {
            this.locationUri = locationUri;
            return this;
        }
        public Builder tags(@Nullable List<LocationFSxOpenZFSTag> tags) {
            this.tags = tags;
            return this;
        }
        public Builder tags(LocationFSxOpenZFSTag... tags) {
            return tags(List.of(tags));
        }        public GetLocationFSxOpenZFSResult build() {
            return new GetLocationFSxOpenZFSResult(locationArn, locationUri, tags);
        }
    }
}
