// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.azurenative.compute.outputs;

import com.pulumi.azurenative.compute.outputs.EncryptionSetIdentityResponse;
import com.pulumi.azurenative.compute.outputs.KeyForDiskEncryptionSetResponse;
import com.pulumi.core.annotations.CustomType;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetDiskEncryptionSetResult {
        /**
         * @return The key vault key which is currently used by this disk encryption set.
         * 
         */
    private final @Nullable KeyForDiskEncryptionSetResponse activeKey;
        /**
         * @return The type of key used to encrypt the data of the disk.
         * 
         */
    private final @Nullable String encryptionType;
        /**
         * @return Resource Id
         * 
         */
    private final String id;
        /**
         * @return The managed identity for the disk encryption set. It should be given permission on the key vault before it can be used to encrypt disks.
         * 
         */
    private final @Nullable EncryptionSetIdentityResponse identity;
        /**
         * @return The time when the active key of this disk encryption set was updated.
         * 
         */
    private final String lastKeyRotationTimestamp;
        /**
         * @return Resource location
         * 
         */
    private final String location;
        /**
         * @return Resource name
         * 
         */
    private final String name;
        /**
         * @return A readonly collection of key vault keys previously used by this disk encryption set while a key rotation is in progress. It will be empty if there is no ongoing key rotation.
         * 
         */
    private final List<KeyForDiskEncryptionSetResponse> previousKeys;
        /**
         * @return The disk encryption set provisioning state.
         * 
         */
    private final String provisioningState;
        /**
         * @return Set this flag to true to enable auto-updating of this disk encryption set to the latest key version.
         * 
         */
    private final @Nullable Boolean rotationToLatestKeyVersionEnabled;
        /**
         * @return Resource tags
         * 
         */
    private final @Nullable Map<String,String> tags;
        /**
         * @return Resource type
         * 
         */
    private final String type;

    @CustomType.Constructor
    private GetDiskEncryptionSetResult(
        @CustomType.Parameter("activeKey") @Nullable KeyForDiskEncryptionSetResponse activeKey,
        @CustomType.Parameter("encryptionType") @Nullable String encryptionType,
        @CustomType.Parameter("id") String id,
        @CustomType.Parameter("identity") @Nullable EncryptionSetIdentityResponse identity,
        @CustomType.Parameter("lastKeyRotationTimestamp") String lastKeyRotationTimestamp,
        @CustomType.Parameter("location") String location,
        @CustomType.Parameter("name") String name,
        @CustomType.Parameter("previousKeys") List<KeyForDiskEncryptionSetResponse> previousKeys,
        @CustomType.Parameter("provisioningState") String provisioningState,
        @CustomType.Parameter("rotationToLatestKeyVersionEnabled") @Nullable Boolean rotationToLatestKeyVersionEnabled,
        @CustomType.Parameter("tags") @Nullable Map<String,String> tags,
        @CustomType.Parameter("type") String type) {
        this.activeKey = activeKey;
        this.encryptionType = encryptionType;
        this.id = id;
        this.identity = identity;
        this.lastKeyRotationTimestamp = lastKeyRotationTimestamp;
        this.location = location;
        this.name = name;
        this.previousKeys = previousKeys;
        this.provisioningState = provisioningState;
        this.rotationToLatestKeyVersionEnabled = rotationToLatestKeyVersionEnabled;
        this.tags = tags;
        this.type = type;
    }

    /**
     * @return The key vault key which is currently used by this disk encryption set.
     * 
     */
    public Optional<KeyForDiskEncryptionSetResponse> activeKey() {
        return Optional.ofNullable(this.activeKey);
    }
    /**
     * @return The type of key used to encrypt the data of the disk.
     * 
     */
    public Optional<String> encryptionType() {
        return Optional.ofNullable(this.encryptionType);
    }
    /**
     * @return Resource Id
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return The managed identity for the disk encryption set. It should be given permission on the key vault before it can be used to encrypt disks.
     * 
     */
    public Optional<EncryptionSetIdentityResponse> identity() {
        return Optional.ofNullable(this.identity);
    }
    /**
     * @return The time when the active key of this disk encryption set was updated.
     * 
     */
    public String lastKeyRotationTimestamp() {
        return this.lastKeyRotationTimestamp;
    }
    /**
     * @return Resource location
     * 
     */
    public String location() {
        return this.location;
    }
    /**
     * @return Resource name
     * 
     */
    public String name() {
        return this.name;
    }
    /**
     * @return A readonly collection of key vault keys previously used by this disk encryption set while a key rotation is in progress. It will be empty if there is no ongoing key rotation.
     * 
     */
    public List<KeyForDiskEncryptionSetResponse> previousKeys() {
        return this.previousKeys;
    }
    /**
     * @return The disk encryption set provisioning state.
     * 
     */
    public String provisioningState() {
        return this.provisioningState;
    }
    /**
     * @return Set this flag to true to enable auto-updating of this disk encryption set to the latest key version.
     * 
     */
    public Optional<Boolean> rotationToLatestKeyVersionEnabled() {
        return Optional.ofNullable(this.rotationToLatestKeyVersionEnabled);
    }
    /**
     * @return Resource tags
     * 
     */
    public Map<String,String> tags() {
        return this.tags == null ? Map.of() : this.tags;
    }
    /**
     * @return Resource type
     * 
     */
    public String type() {
        return this.type;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetDiskEncryptionSetResult defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable KeyForDiskEncryptionSetResponse activeKey;
        private @Nullable String encryptionType;
        private String id;
        private @Nullable EncryptionSetIdentityResponse identity;
        private String lastKeyRotationTimestamp;
        private String location;
        private String name;
        private List<KeyForDiskEncryptionSetResponse> previousKeys;
        private String provisioningState;
        private @Nullable Boolean rotationToLatestKeyVersionEnabled;
        private @Nullable Map<String,String> tags;
        private String type;

        public Builder() {
    	      // Empty
        }

        public Builder(GetDiskEncryptionSetResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.activeKey = defaults.activeKey;
    	      this.encryptionType = defaults.encryptionType;
    	      this.id = defaults.id;
    	      this.identity = defaults.identity;
    	      this.lastKeyRotationTimestamp = defaults.lastKeyRotationTimestamp;
    	      this.location = defaults.location;
    	      this.name = defaults.name;
    	      this.previousKeys = defaults.previousKeys;
    	      this.provisioningState = defaults.provisioningState;
    	      this.rotationToLatestKeyVersionEnabled = defaults.rotationToLatestKeyVersionEnabled;
    	      this.tags = defaults.tags;
    	      this.type = defaults.type;
        }

        public Builder activeKey(@Nullable KeyForDiskEncryptionSetResponse activeKey) {
            this.activeKey = activeKey;
            return this;
        }
        public Builder encryptionType(@Nullable String encryptionType) {
            this.encryptionType = encryptionType;
            return this;
        }
        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }
        public Builder identity(@Nullable EncryptionSetIdentityResponse identity) {
            this.identity = identity;
            return this;
        }
        public Builder lastKeyRotationTimestamp(String lastKeyRotationTimestamp) {
            this.lastKeyRotationTimestamp = Objects.requireNonNull(lastKeyRotationTimestamp);
            return this;
        }
        public Builder location(String location) {
            this.location = Objects.requireNonNull(location);
            return this;
        }
        public Builder name(String name) {
            this.name = Objects.requireNonNull(name);
            return this;
        }
        public Builder previousKeys(List<KeyForDiskEncryptionSetResponse> previousKeys) {
            this.previousKeys = Objects.requireNonNull(previousKeys);
            return this;
        }
        public Builder previousKeys(KeyForDiskEncryptionSetResponse... previousKeys) {
            return previousKeys(List.of(previousKeys));
        }
        public Builder provisioningState(String provisioningState) {
            this.provisioningState = Objects.requireNonNull(provisioningState);
            return this;
        }
        public Builder rotationToLatestKeyVersionEnabled(@Nullable Boolean rotationToLatestKeyVersionEnabled) {
            this.rotationToLatestKeyVersionEnabled = rotationToLatestKeyVersionEnabled;
            return this;
        }
        public Builder tags(@Nullable Map<String,String> tags) {
            this.tags = tags;
            return this;
        }
        public Builder type(String type) {
            this.type = Objects.requireNonNull(type);
            return this;
        }        public GetDiskEncryptionSetResult build() {
            return new GetDiskEncryptionSetResult(activeKey, encryptionType, id, identity, lastKeyRotationTimestamp, location, name, previousKeys, provisioningState, rotationToLatestKeyVersionEnabled, tags, type);
        }
    }
}
