// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.azurenative.web;

import io.pulumi.azurenative.Utilities;
import io.pulumi.azurenative.web.inputs.GetWebAppSourceControlSlotArgs;
import io.pulumi.azurenative.web.outputs.GetWebAppSourceControlSlotResult;
import io.pulumi.core.internal.Reflection.TypeShape;
import io.pulumi.deployment.Deployment;
import io.pulumi.deployment.InvokeOptions;
import java.util.concurrent.CompletableFuture;
import javax.annotation.Nullable;

public class GetWebAppSourceControlSlot {
/**
 * Source control configuration for an app.
API Version: 2020-12-01.
 *
 * Source control configuration for an app.
 */
    public static CompletableFuture<GetWebAppSourceControlSlotResult> invokeAsync(GetWebAppSourceControlSlotArgs args, @Nullable InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("azure-native:web:getWebAppSourceControlSlot", TypeShape.of(GetWebAppSourceControlSlotResult.class), args == null ? GetWebAppSourceControlSlotArgs.Empty : args, Utilities.withVersion(options));
    }
}
