on:
  push:
    branches: [main]
    paths: [CHANGELOG.md]
  workflow_dispatch: {}

permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.PULUMI_BOT_TOKEN }}

jobs:
  release-pulumi-language-java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Fetch Tags
        run: |
          git fetch --quiet --prune --unshallow --tags
      - name: Setup mise and install tools
        uses: jdx/mise-action@v3.4.0
      - name: Get the latest version
        id: latest
        uses: miniscruff/changie-action@v2
        with:
          args: latest
      - name: Add env vars
        run: |
          echo GORELEASER_CURRENT_TAG=${{ steps.latest.outputs.output }} >> $GITHUB_ENV
          echo RELEASE_NOTES_PATH=.changes/${{ steps.latest.outputs.output }}.md >> $GITHUB_ENV
      - name: Check if release exists
        id: check-release
        run: |
          if [ -z "$(git tag -l ${{ env.GORELEASER_CURRENT_TAG }})" ]; then
            echo "exists=false" >> "$GITHUB_OUTPUT"
          else
            echo "exists=true" >> "$GITHUB_OUTPUT"
          fi
      - name: Run GoReleaser
        if: steps.check-release.outputs.exists == 'false'
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: -p 3 -f .goreleaser.yml --clean --release-notes=${{ env.RELEASE_NOTES_PATH }}
      - name: Create and push additional tags
        if: steps.check-release.outputs.exists == 'false'
        run: |
          git tag pkg/${{ env.GORELEASER_CURRENT_TAG }}
          git push origin pkg/${{ env.GORELEASER_CURRENT_TAG }}
          git tag sdk/${{ env.GORELEASER_CURRENT_TAG }}
          git push origin sdk/${{ env.GORELEASER_CURRENT_TAG }}
